name: ci

on:
  push:
    branches:
      - 'feat/add-docker-and-tor-support'
  repository_dispatch:
    types: build-sovryntor

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
        with:
          token: ${{ secrets.GA_TOKEN }}
          
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: gambitcajun/sovryn-frontend
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          buildArgs: ci_user_token=${{secrets.GA_TOKEN}}
          addLatest: true
      - name: installing toolset
        run: sudo apt install curl
      - name: trigger sovryntor akash deployment
        run: |-
          curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token {{ secret.TRIGGER_SOVTOR_DEP }}" --request POST --data '{"event_type": "deploy-sovryntor"}' https://api.github.com/repos/neo-dr/e2e-production/dispatches
